language: cpp
before_install:
    - sudo add-apt-repository -y ppa:h-rayflood/llvm
    - sudo apt-get update -qq
install:
    - sudo apt-get install --allow-unauthenticated -qq clang-3.4
    - export CXX="clang++-3.4"
script: make && make test
